/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ling_jnitest_NativeMethods */

#ifndef _Included_ling_jnitest_NativeMethods
#define _Included_ling_jnitest_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ling_jnitest_NativeMethods
 * Method:    printInfo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ling_jnitest_NativeMethods_printInfo
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
